# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

# Setup
title:               A Krevitch To Snork Your Flads
url:                 ""
baseurl:             ""
paginate:            5
github_username:     krstoff
repository: krstoff/krstoff.github.io

theme_credits: "Jekyll theme \"Lanyon\" by Mark Otto."
theme_site: https://github.com/poole/lanyon

markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-relative-links

# Build Settings
exclude:
  - Gemfile
  - Gemfile.lock
