# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

# Setup
title:               A Krevitch To Snork Your Flads
tagline:         "Once upon a time, we weren't trendoids."
url:                 ""
baseurl:             ""
paginate:            5
github_username:     krstoff

theme_credits: "Credit to Mark Otto for the wonderful Jekyll theme \"Lanyon\"."
theme_site: https://github.com/poole/lanyon

gems:
  - jekyll-feed
  - jekyll-relative-links
  
# Build Settings
exclude:
  - Gemfile
  - Gemfile.lock
